apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-prom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-prom-app
  template:
    metadata:
      labels:
        app: go-prom-app
    spec:
      containers:
      - name: go-prom-app
        image: abhirockzz/go-prom-app
        env:
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-prom-app-service
  labels:
    run: go-prom-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: go-prom-app